@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "User" as user {
  *id : INTEGER NOT NULL [PK]
  --
  username : VARCHAR(50)
  email : VARCHAR(255)
  password : text
  date_joined: timestamp
}

entity "Pose" as pose {
  *id : INTEGER NOT NULL [PK]
  --
  sanskrit_name : VARCHAR(50)
  english_name : VARCHAR(50)
  description: text
  benefits : VARCHAR(100)
  img_url_svg : VARCHAR(255)
  img_url_jpg : VARCHAR(255)
  img_url_svg_alt : VARCHAR(255)
  difficultyId : INTEGER  [FK]
}

entity "Category" as category {
  *id : INTEGER NOT NULL [PK]
  --
  category_name : VARCHAR(50)
  description : text
}

entity "Difficulty" as difficulty {
  *id : INTEGER NOT NULL [PK]
  --
  difficulty_level : VARCHAR(50)
}

entity "Session" as session {
  *id : INTEGER NOT NULL [PK]
  --
  title : VARCHAR(255)
  description : text
  duration : INTEGER
  difficultyId : INTEGER  [FK]
}

entity "SessionCustom" as sessionCustom {
  *id : INTEGER NOT NULL [PK]
  --
  title : VARCHAR(255)
  description : text
  duration : INTEGER
  difficultyId : INTEGER  [FK]
  userId : INTEGER  [FK]
}

entity "Launched_Session" as launched_session {
  *userId : INTEGER [PK, FK]
  *sessionId : INTEGER [PK, FK]
  *start_date : date [PK]
  --
  end_date : date
}

entity "Pose_Category" {
  *poseId : INTEGER [FK]
  *categoryId : INTEGER [FK]
}

entity "Session_Pose" {
  *sessionId : INTEGER [FK]
  *poseId : INTEGER [FK]
}

entity "SessionCustom_Pose" {
  *sessionCustomId : INTEGER [FK]
  *poseId : INTEGER [FK]
}

user }o---o{ session
user }o--|| sessionCustom 
session }|---|{ pose 
session ||--o{ difficulty 
pose }o--o{ category 

user }--o{ launched_session 
session }--o{ launched_session 

pose }--|| Pose_Category 
Pose_Category }--|| category

pose }--|| Session_Pose  
Session_Pose }--|| session

pose }---|| SessionCustom_Pose 
SessionCustom_Pose }--|| sessionCustom

@enduml
